version: 2

tables:
  - name: schema_version
    columns:
      - name: version
        type: integer
        not_null: true

  # Tier 1: Investigation-scoped entities

  - name: investigation_suites
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: name
        type: text
        not_null: true
      - name: description
        type: text
      - name: status
        type: text
        not_null: true
        default: "'open'"
      - name: created_at
        type: text
        not_null: true
      - name: closed_at
        type: text

  - name: versions
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: label
        type: text
        not_null: true
        unique: true
      - name: ocp_build
        type: text

  - name: pipelines
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: suite_id
        type: integer
        not_null: true
        references: "investigation_suites(id)"
      - name: version_id
        type: integer
        not_null: true
        references: "versions(id)"
      - name: name
        type: text
        not_null: true
      - name: rp_launch_id
        type: integer
      - name: status
        type: text
        not_null: true
      - name: started_at
        type: text
      - name: ended_at
        type: text

  - name: launches
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: pipeline_id
        type: integer
        not_null: true
        references: "pipelines(id)"
      - name: rp_launch_id
        type: integer
        not_null: true
      - name: rp_launch_uuid
        type: text
      - name: name
        type: text
      - name: status
        type: text
      - name: started_at
        type: text
      - name: ended_at
        type: text
      - name: env_attributes
        type: text
      - name: git_branch
        type: text
      - name: git_commit
        type: text
      - name: envelope_payload
        type: blob
    unique:
      - [pipeline_id, rp_launch_id]

  - name: jobs
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: launch_id
        type: integer
        not_null: true
        references: "launches(id)"
      - name: rp_item_id
        type: integer
        not_null: true
      - name: name
        type: text
        not_null: true
      - name: clock_type
        type: text
      - name: status
        type: text
      - name: stats_total
        type: integer
      - name: stats_failed
        type: integer
      - name: stats_passed
        type: integer
      - name: stats_skipped
        type: integer
      - name: started_at
        type: text
      - name: ended_at
        type: text
    unique:
      - [launch_id, rp_item_id]

  - name: cases
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: job_id
        type: integer
        not_null: true
        references: "jobs(id)"
      - name: launch_id
        type: integer
        not_null: true
        references: "launches(id)"
      - name: rp_item_id
        type: integer
        not_null: true
      - name: name
        type: text
        not_null: true
        default: "''"
      - name: polarion_id
        type: text
      - name: status
        type: text
        not_null: true
        default: "'open'"
      - name: symptom_id
        type: integer
        references: "symptoms(id)"
      - name: rca_id
        type: integer
        references: "rcas(id)"
      - name: error_message
        type: text
      - name: log_snippet
        type: text
      - name: log_truncated
        type: integer
        default: "0"
      - name: started_at
        type: text
      - name: ended_at
        type: text
      - name: created_at
        type: text
        not_null: true
      - name: updated_at
        type: text
        not_null: true
    unique:
      - [launch_id, rp_item_id]

  - name: triages
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: case_id
        type: integer
        not_null: true
        unique: true
        references: "cases(id)"
      - name: symptom_category
        type: text
        not_null: true
      - name: severity
        type: text
      - name: defect_type_hypothesis
        type: text
      - name: skip_investigation
        type: integer
        default: "0"
      - name: clock_skew_suspected
        type: integer
        default: "0"
      - name: cascade_suspected
        type: integer
        default: "0"
      - name: candidate_repos
        type: text
      - name: data_quality_notes
        type: text
      - name: created_at
        type: text
        not_null: true

  # Tier 2: Global knowledge entities

  - name: symptoms
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: fingerprint
        type: text
        not_null: true
        unique: true
      - name: name
        type: text
        not_null: true
      - name: description
        type: text
      - name: error_pattern
        type: text
      - name: test_name_pattern
        type: text
      - name: component
        type: text
      - name: severity
        type: text
      - name: first_seen_at
        type: text
        not_null: true
      - name: last_seen_at
        type: text
        not_null: true
      - name: occurrence_count
        type: integer
        not_null: true
        default: "1"
      - name: status
        type: text
        not_null: true
        default: "'active'"

  - name: rcas
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: title
        type: text
        not_null: true
      - name: description
        type: text
        not_null: true
        default: "''"
      - name: defect_type
        type: text
        not_null: true
      - name: category
        type: text
      - name: component
        type: text
      - name: affected_versions
        type: text
      - name: evidence_refs
        type: text
      - name: convergence_score
        type: real
      - name: jira_ticket_id
        type: text
      - name: jira_link
        type: text
      - name: status
        type: text
        not_null: true
        default: "'open'"
      - name: created_at
        type: text
        not_null: true
      - name: resolved_at
        type: text
      - name: verified_at
        type: text
      - name: archived_at
        type: text

  - name: symptom_rca
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: symptom_id
        type: integer
        not_null: true
        references: "symptoms(id)"
      - name: rca_id
        type: integer
        not_null: true
        references: "rcas(id)"
      - name: confidence
        type: real
      - name: notes
        type: text
      - name: linked_at
        type: text
        not_null: true
    unique:
      - [symptom_id, rca_id]

indexes:
  - name: idx_cases_symptom
    table: cases
    columns: [symptom_id]
  - name: idx_cases_rca
    table: cases
    columns: [rca_id]
  - name: idx_cases_launch
    table: cases
    columns: [launch_id]
  - name: idx_cases_job
    table: cases
    columns: [job_id]
  - name: idx_pipelines_suite
    table: pipelines
    columns: [suite_id]
  - name: idx_launches_pipeline
    table: launches
    columns: [pipeline_id]
  - name: idx_jobs_launch
    table: jobs
    columns: [launch_id]
  - name: idx_symptoms_fingerprint
    table: symptoms
    columns: [fingerprint]
  - name: idx_symptom_rca_symptom
    table: symptom_rca
    columns: [symptom_id]
  - name: idx_symptom_rca_rca
    table: symptom_rca
    columns: [rca_id]
